### ISSUE TITLE
MapQuest - Direct tile access

### ISSUE THREAD

**Issue by TuxCoding** [freifunk-darmstadt/meshviewer#1]
![map_quest](https://cloud.githubusercontent.com/assets/1957196/16894440/6986250c-4b56-11e6-84e6-389faa156c91.png)

**Comment by mweinelt** [comment]
Hi,

wir haben bereits HopGlass eingerichtet, müssen nur noch das DNS umbiegen und das Zertifikat besorgen. Benutze doch solange bitte den OSM Layer auf der aktuellen Karte.

Beste Grüße, Martin

**Comment by TuxCoding** [comment]
Ok, danke für die schnelle Info.
